# The Site Configuration
theme: jekyll-theme-chirpy

baseurl: '/'

lang: pt-BR

prefer_datetime_locale:

timezone: America/Sao_Paulo

title: Marcos Pereira

tagline: Software Expert (Technical Manager) no Mercado Livre

description: >-
  Blog com experiências profissionais e pessoais :)

url: 'http://marcospereirajr.com.br'

github:
  username: marcospereirampj

twitter:
  username: _marcos_pereira

social:
  name: Marcos Pereira
  email: marcospereira.mpj@gmail.com
  links:
    - https://twitter.com/_marcos_pereira
    - https://github.com/marcospereirampj
    # - https://www.facebook.com/username
    - https://www.linkedin.com/in/marcospereirampj

google_site_verification:

google_analytics:
  id:
  pv:
    proxy_endpoint:
    cache_path:

theme_mode: light
img_cdn:

avatar: /assets/img/profile/avatar.jpg

toc: true

comments:
  active: disqus
  disqus:
    shortname: http-marcospereirajr-com-br

assets:
  self_host:
    enabled: true
    env: # [development|production]

pwa:
  enabled: true   # the option for PWA feature

paginate: 10

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
